name: Amul Stock Checker
on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:       # Allows manual triggering

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 5     # Prevents hanging jobs
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Updated to v3
        
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          cache: 'pip'      # Caches dependencies for faster runs
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip list         # Debug: Show installed packages
          
      - name: Verify environment
        run: |
          python -c "import requests, bs4; print('All imports work!')"
          
      - name: Run stock checker
        run: |
          python amul_alert.py || echo "Script failed" && exit 1